import { N } from "@/engine/math/num";

export const CHAOTIC_ETHER_EXTRACT_REQUIREMENT = N(100);
export const CHAOTIC_ETHER_EXTRACT_LOG_DIVISOR = N(4);
export const CHAOTIC_ETHER_EXTRACT_ACCELERATION_START = N(5);
export const CHAOTIC_ETHER_EXTRACT_ACCELERATION_POWER = N(2);
