import { N } from "@/engine/math/num";

export const CONCEPT_CRYSTAL_BASE_PRODUCTION_INTERVAL_SEC = N(15);
export const CONCEPT_CRYSTAL_INTERVAL_UPGRADE_REQUIREMENT = N("1e29");
export const CONCEPT_CRYSTAL_INTERVAL_UPGRADE_REQUIREMENT_SCALE = N(10);
export const CONCEPT_CRYSTAL_INTERVAL_REDUCTION = N(0.85);
