import { N, ONE, div, pow } from "@/engine/math/num";

export const CONCEPT_CRYSTAL_BASE_PRODUCTION_INTERVAL_SEC = N(30);
export const CONCEPT_CRYSTAL_INTERVAL_UPGRADE_REQUIREMENT = N("1e29");
export const CONCEPT_CRYSTAL_INTERVAL_UPGRADE_REQUIREMENT_SCALE = N(10);
export const CONCEPT_CRYSTAL_INTERVAL_REDUCTION = N(0.91);
export const CONCEPT_CRYSTAL_CONDENSE_DREAM_CRYSTAL_TIER = 8;
export const CONCEPT_CRYSTAL_NODE_HARDCAP = pow(N(2), 1024);

export const CONCEPT_CRYSTAL_NODE_MAGNITUDE_POWER = N(1.05);
export const CONCEPT_CRYSTAL_NODE_BASE_LOG_WEIGHT = N(0.035);
export const CONCEPT_CRYSTAL_NODE_SCALE_LOG_WEIGHT = N(0.0425);
export const CONCEPT_CRYSTAL_NODE_PER_CRYSTAL_LOG_WEIGHT = N(0.065);
export const CONCEPT_CRYSTAL_DC_COST_SCALE = div(N(2), N(3));
export const CONCEPT_CRYSTAL_DC_COST_LOG_POWER = div(ONE, N(4));
export const CONCEPT_CRYSTAL_STANDARD_EFFECT_LOG_POWER = N(Math.LN10);
export const CONCEPT_CRYSTAL_CP_GAIN_SCALE = N(5);
export const CONCEPT_CRYSTAL_ASSIMILATION_SCALE = div(ONE, N(5));
