import { N } from "../num"

export const DREAM_ENERGY_SOFTCAP_ONE_START = N(2147483647)
export const DREAM_ENERGY_SOFTCAP_POWER_DISPLAY = N(10)
export const DREAM_ENERGY_SOFTCAP_ONE_DEFAULT_POWER = N(0.6);
export const DREAM_ENERGY_SOFTCAP_TWO_START = N("9223372036854775808");
export const DREAM_ENERGY_SOFTCAP_TWO_STRENGTH_BASE = N(10);
export const DREAM_ENERGY_SOFTCAP_TWO_STRENGTH_GROWTH = N(10);
export const DREAM_ENERGY_SOFTCAP_TWO_EFFECT_SCALE = N(0.5);
export const DREAM_ENERGY_SOFTCAP_THREE_START = N("1e28");
export const DREAM_ENERGY_SOFTCAP_THREE_STRENGTH_BASE = N(10);
export const DREAM_ENERGY_SOFTCAP_THREE_STRENGTH_GROWTH = N(9);
