import type { Num } from "../num"
import { N, div } from "../num"

export const DREAM_ENERGY_SOFTCAP_ONE_START = N(2147483647)
export const DREAM_ENERGY_SOFTCAP_POWER_DISPLAY = N(10)
export const DREAM_ENERGY_SOFTCAP_ONE_DEFAULT_SCALE = div(N(20), N(3));
export const DREAM_ENERGY_SOFTCAP_TWO_START = N("9223372036854775808");
export const DREAM_ENERGY_SOFTCAP_TWO_STRENGTH_BASE = N(10);
export const DREAM_ENERGY_SOFTCAP_TWO_STRENGTH_GROWTH = N(5);
